import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Feed from "../components/Feed";
import { useContext } from "react";
import { AuthContext } from "../context/auth";
import { useRouter } from "next/router";
export default function Home() {
  const { user } = useContext(AuthContext);
  const Redirect = () => {
    const router = useRouter();
    router.push("/login");
  };
  console.log("feed", user);
  return (
    <div className={styles.container}>
      <Head>
        <title>Reels App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/instagram-reels.png" />
        {/* Google Fonts */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto&display=swap"
          rel="stylesheet"
        />
      </Head>
      {user?.uid ? <Feed /> : <Redirect />}
    </div>
  );
}
